# Generated by Django 3.0.2 on 2020-01-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swdestinybot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackToken',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='set_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
